### ISSUE TITLE
Removing the name of a problematic person from a lab

### ISSUE THREAD

**Issue by dovid11564** [learn-co-curriculum/phase-3-ruby-oo-basics-setter-and-getter-methods#5]
### Canvas Link

https://learning.flatironschool.com/courses/5243/assignments/216918?module_item_id=504816

### Concern

Maybe it's just me, but as a Jew I was not happy to see Kanye's name here in light of recent events. Really didn't want to have to think about him or his ilk today. His name appears on lines 52, 53, 71, 72, 77, and 81

### Suggested Changes

Swap out his name for any literally any other

**Comment by jlboba** [comment]
Hello, thank you for bringing this up! I completely agree and have gone ahead and changed the example.
